// File: backend/SchoolManagement.Tests/UnitTests/AuthorizationCoverageTests.cs
//
// Reflection-based tests that enforce two security invariants:
//
// 1. Every controller action method is either protected by an
//    [Authorize] attribute (class or method level) or explicitly
//    marked [AllowAnonymous].  No action may rely on the FallbackPolicy
//    alone — that is a safety net, not the primary protection.
//
// 2. Every policy name referenced in [Authorize(Policy = "...")] is
//    either a permission in Permissions.All (auto-generated by the
//    PermissionPolicyProvider) or a manually registered composite
//    policy like "Attendance.Write".
//
// If either test fails, a developer added an endpoint without thinking
// about access control, or referenced a permission that doesn't exist.

using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SchoolManagement.Domain.Constants;
using Xunit;

namespace SchoolManagement.Tests.UnitTests;

public class AuthorizationCoverageTests
{
    // Manually registered composite policies that are NOT single-
    // permission names.  Add to this list whenever you register a
    // composite policy in Program.cs.
    private static readonly HashSet<string> CompositePolices = new()
    {
        "Attendance.Write"
    };

    /// <summary>
    /// Returns all controller types in the API assembly.
    /// </summary>
    private static IEnumerable<Type> GetControllerTypes()
    {
        // Load the API assembly by locating a known controller type.
        var assembly = typeof(SchoolManagement.API.Controllers.AuthController).Assembly;
        return assembly.GetTypes()
            .Where(t => typeof(ControllerBase).IsAssignableFrom(t)
                        && !t.IsAbstract
                        && t.IsPublic);
    }

    /// <summary>
    /// Returns action methods (public instance methods that could be
    /// endpoints) on a controller type.
    /// </summary>
    private static IEnumerable<MethodInfo> GetActionMethods(Type controllerType)
    {
        return controllerType.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly)
            .Where(m => !m.IsSpecialName); // exclude property getters/setters
    }

    [Fact]
    public void EveryAction_IsProtectedOrAllowAnonymous()
    {
        var unprotectedActions = new List<string>();

        foreach (var controller in GetControllerTypes())
        {
            var classHasAuthorize = controller
                .GetCustomAttributes<AuthorizeAttribute>().Any();

            foreach (var method in GetActionMethods(controller))
            {
                var hasAllowAnonymous = method
                    .GetCustomAttributes<AllowAnonymousAttribute>().Any();
                var hasMethodAuthorize = method
                    .GetCustomAttributes<AuthorizeAttribute>().Any();

                // Protected = class-level [Authorize] OR method-level [Authorize]
                // Exempt    = [AllowAnonymous]
                var isProtected = classHasAuthorize || hasMethodAuthorize;
                var isExempt = hasAllowAnonymous;

                if (!isProtected && !isExempt)
                {
                    unprotectedActions.Add(
                        $"{controller.Name}.{method.Name}");
                }
            }
        }

        Assert.True(
            unprotectedActions.Count == 0,
            $"The following actions rely on the FallbackPolicy only. " +
            $"Add [Authorize] or [Authorize(Policy = \"...\")] to the " +
            $"method or its controller class, or [AllowAnonymous] if " +
            $"intentionally public:\n  " +
            string.Join("\n  ", unprotectedActions));
    }

    [Fact]
    public void EveryPolicyName_ExistsInPermissionsCatalog()
    {
        var unknownPolicies = new List<string>();

        foreach (var controller in GetControllerTypes())
        {
            // Collect policy names from both class-level and method-level attributes.
            var classAuthorize = controller
                .GetCustomAttributes<AuthorizeAttribute>();

            foreach (var attr in classAuthorize)
            {
                if (!string.IsNullOrEmpty(attr.Policy))
                    CheckPolicy(attr.Policy, $"{controller.Name} (class)", unknownPolicies);
            }

            foreach (var method in GetActionMethods(controller))
            {
                var methodAuthorize = method
                    .GetCustomAttributes<AuthorizeAttribute>();

                foreach (var attr in methodAuthorize)
                {
                    if (!string.IsNullOrEmpty(attr.Policy))
                        CheckPolicy(attr.Policy, $"{controller.Name}.{method.Name}", unknownPolicies);
                }
            }
        }

        Assert.True(
            unknownPolicies.Count == 0,
            $"The following [Authorize] policy names are not in " +
            $"Permissions.All and not in the composite-policy list. " +
            $"Either add the permission to Permissions.cs or register " +
            $"a composite policy in Program.cs:\n  " +
            string.Join("\n  ", unknownPolicies));
    }

    private static void CheckPolicy(string policyName, string location, List<string> unknowns)
    {
        if (!Permissions.All.Contains(policyName) && !CompositePolices.Contains(policyName))
        {
            unknowns.Add($"{location} → \"{policyName}\"");
        }
    }
}
