export const SUBJECT_TYPES = ["Theory", "Practical", "Both"] as const;
export type SubjectType = (typeof SUBJECT_TYPES)[number];

export interface SubjectResponse {
  id: number;
  name: string;
  code: string;
  classSectionId: number;
  classSectionName: string;
  type: SubjectType | string;
  maxMarks: number | null;
  passMarks: number | null;
  theoryMax: number | null;
  theoryPass: number | null;
  practicalMax: number | null;
  practicalPass: number | null;
  status: string;
  teacherId: number | null;
  teacherName: string | null;
}

// Create and update take the same fields.
export interface SubjectRequest {
  name: string;
  code: string | null; // null/blank = auto-generated by the backend
  classSectionId: number;
  type: SubjectType;
  maxMarks: number | null;
  passMarks: number | null;
  theoryMax: number | null;
  theoryPass: number | null;
  practicalMax: number | null;
  practicalPass: number | null;
  isActive: boolean;
}
